# Generated by Django 2.2.5 on 2019-11-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('site', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('user_created', models.CharField(max_length=255)),
            ],
        ),
    ]
